/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseConfirmContainer: typeof import('./components/base/BaseConfirmContainer.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseLanguageSwitcher: typeof import('./components/base/BaseLanguageSwitcher.vue')['default']
    BaseModal: typeof import('./components/base/BaseModal.vue')['default']
    BaseSkeleton: typeof import('./components/base/BaseSkeleton.vue')['default']
    BaseToastContainer: typeof import('./components/base/BaseToastContainer.vue')['default']
    CartDrawer: typeof import('./components/client/cart/CartDrawer.vue')['default']
    CheckoutAddressStep: typeof import('./components/client/checkout/CheckoutAddressStep.vue')['default']
    CheckoutPaymentStep: typeof import('./components/client/checkout/CheckoutPaymentStep.vue')['default']
    CheckoutReviewStep: typeof import('./components/client/checkout/CheckoutReviewStep.vue')['default']
    CheckoutStepper: typeof import('./components/client/checkout/CheckoutStepper.vue')['default']
    ClientHeader: typeof import('./components/client/layout/ClientHeader.vue')['default']
    GoodsReceiptForm: typeof import('./components/admin/GoodsReceiptForm.vue')['default']
    HeroSection: typeof import('./components/client/home/HeroSection.vue')['default']
    ProductCard: typeof import('./components/client/product/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
